# -*- coding: utf-8 -*-
"""chetan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BeO7sWWA-vjx52EfJfDrvyji6voJAGjX
"""

addition=lambda x,y:x+y
print("the addition of 3 and 8 is:",addition(3,8))  #addition

substraction=lambda x,y:x-y
print("the substraction of 4 and 8 is:",substraction(4,8))  #substraction

nums = [1,2,3,4,5,6,7,8,9,10]
print("original list of integers:")
print(nums)
print("\nsquare every number of the said list:")
square_nums=list(map(lambda x:x**2,nums))
print(square_nums)
print("\nCube every number of the said list:")
Cube_nums=list(map(lambda x:x**3,nums))
print(Cube_nums)

def func_compute(n):  # four practicale
  return lambda x :x*n
result=func_compute(2)
print("Double the number of 15=" ,result(15))
result=func_compute(3)
print("triple the number of 15=" ,result(15))
result=func_compute(4)
print("Quadruple the number of 15=" ,result(15))



starts_with = lambda x:True if x.startswith('I') else  False
print(starts_with(India))